# Generates src/haven/automated/lp/LpSpec.java from nurgling2 VSpec.java data.
# Phase 1 writes the file; phase 2 rechunks the object block at species boundaries
# so no ArrayList local is split from its object.put() across method borders.
# Usage: python tools/gen-lpspec.py   (expects the nurgling2 checkout at the path below)
import re, io

src = open(r"C:\Users\james\Desktop\Haven\Clients\nurgling2\src\nurgling\tools\VSpec.java", encoding="utf-8", errors="replace").readlines()

# --- object block: from first 'static {' to the line before 'static {' of categories ---
start = next(i for i,l in enumerate(src) if l.strip()=="static {")
# find matching close: track braces
depth=0; end=None
for i in range(start, len(src)):
    depth += src[i].count("{") - src[i].count("}")
    if depth==0 and i>start: end=i; break
obj_lines = src[start+1:end]
# strip non-ascii comments, keep code
clean=[]
for l in obj_lines:
    code = l.rstrip("\n")
    if "//" in code:
        code = code.split("//")[0].rstrip()
        if not code.strip(): continue
    if code.strip(): clean.append(code)

# --- categories: extract (name, static) pairs and per-category name lists ---
pairs=[]; cats={}
cur=[]; text="".join(src)
for m in re.finditer(r'(\w+)\.add\(new JSONObject\("(\{.*?\})"\)\);', text):
    var, js = m.group(1), m.group(2).replace('\\"','"')
    nm = re.search(r'"name":"([^"]+)"', js)
    st = re.search(r'"static":"([^"]+)"', js)
    if nm:
        cats.setdefault(var, []).append(nm.group(1))
        if st: pairs.append((nm.group(1), st.group(1)))
# map var name -> category key from categories.put("Key", var)
varkey={}
for m in re.finditer(r'categories\.put\("([^"]+)",\s*(\w+)\);', text):
    varkey[m.group(2)] = m.group(1)

out = io.StringIO()
out.write("""package haven.automated.lp;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;

/**
 * Static discovery data for the LP-assistant, extracted from nurgling2's VSpec.java
 * (generated by tools/gen-lpspec.py - regenerate rather than hand-edit the tables):
 *  - object:      world resource name -> the LP-discoverable product item names it yields.
 *                 Kritter resnames are NESTED (gfx/kritter/grasshopper/grasshopper).
 *  - productIcon: product item name -> inventory icon resource path (from the category data;
 *                 multi-frame "layer" entries are omitted, callers fall back to a generic marker).
 *  - category:    category name -> product item names (used e.g. for seed-pick resolution).
 * SAFETY invariant carried over: only non-aggressive targets may appear in object - the
 * auto-LP bot chases everything in it.
 */
public class LpSpec {
    public static final HashMap<String, ArrayList<String>> object = new HashMap<>();
    public static final HashMap<String, String> productIcon = new HashMap<>();
    public static final HashMap<String, ArrayList<String>> category = new HashMap<>();

    private static Map1(){}
""".replace("    private static Map1(){}\n",""))

# object init, chunked to stay far under the 64KB bytecode-per-method limit
chunk=250; n=0; funcs=[]
for i in range(0, len(clean), chunk):
    n+=1; funcs.append(f"initObject{n}")
    out.write(f"    private static void initObject{n}() {{\n")
    for l in clean[i:i+chunk]:
        out.write("    "+l+"\n")
    out.write("    }\n\n")

out.write("    private static void initIcons() {\n")
seen=set()
for nm,st in pairs:
    if nm in seen: continue
    seen.add(nm)
    out.write(f'        productIcon.put("{nm}", "{st}");\n')
out.write("    }\n\n")

out.write("    private static void initCategories() {\n")
for var,names in cats.items():
    key = varkey.get(var)
    if not key: continue
    lst = ", ".join(f'"{x}"' for x in dict.fromkeys(names))
    out.write(f'        category.put("{key}", new ArrayList<>(Arrays.asList({lst})));\n')
out.write("    }\n\n    static {\n")
for f in funcs: out.write(f"        {f}();\n")
out.write("        initIcons();\n        initCategories();\n    }\n")

out.write("""
    /** Icon resource path for a product item name, or null (caller falls back to a generic marker). */
    public static String getIconPath(String name) {
        return name == null ? null : productIcon.get(name);
    }

    public static List<String> getCategoryContent(String name) {
        ArrayList<String> r = category.get(name);
        return r == null ? new ArrayList<>() : r;
    }
}
""")
open(r"C:\Users\james\Desktop\Haven\Clients\Novocaine\src\haven\automated\lp\LpSpec.java","w",encoding="utf-8").write(out.getvalue())
print("object lines:", len(clean), "| icon pairs:", len(seen), "| categories:", len(varkey))

# ---- phase 2: rechunk at species-group boundaries ----
